<?php

namespace AppBundle\Repository;

/**
 * domenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class domenaRepository extends \Doctrine\ORM\EntityRepository
{
}
