<?php

namespace AppBundle\Repository;

/**
 * FirmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmaRepository extends \Doctrine\ORM\EntityRepository
{
}
