<?php

namespace AppBundle\Repository;

/**
 * kontoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kontoRepository extends \Doctrine\ORM\EntityRepository
{
}
