<?php

namespace AppBundle\Repository;

/**
 * serwerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serwerRepository extends \Doctrine\ORM\EntityRepository
{
}
