<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Firma extends \AppBundle\Entity\Firma implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'nazwa', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'adres', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'nip', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'regon', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'tel', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'inne', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'kontoId'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'nazwa', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'adres', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'nip', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'regon', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'tel', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'inne', '' . "\0" . 'AppBundle\\Entity\\Firma' . "\0" . 'kontoId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Firma $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazwa($nazwa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazwa', [$nazwa]);

        return parent::setNazwa($nazwa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazwa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazwa', []);

        return parent::getNazwa();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdres($adres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdres', [$adres]);

        return parent::setAdres($adres);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdres', []);

        return parent::getAdres();
    }

    /**
     * {@inheritDoc}
     */
    public function setNip($nip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNip', [$nip]);

        return parent::setNip($nip);
    }

    /**
     * {@inheritDoc}
     */
    public function getNip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNip', []);

        return parent::getNip();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegon($regon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegon', [$regon]);

        return parent::setRegon($regon);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegon', []);

        return parent::getRegon();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setInne($inne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInne', [$inne]);

        return parent::setInne($inne);
    }

    /**
     * {@inheritDoc}
     */
    public function getInne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInne', []);

        return parent::getInne();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontoId($kontoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontoId', [$kontoId]);

        return parent::setKontoId($kontoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontoId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontoId', []);

        return parent::getKontoId();
    }

}
