<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class domena extends \AppBundle\Entity\domena implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'nazwa', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'opis', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'firma', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'serwer', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'kontoId', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'dataWyg', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'aktywna', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'inne'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'nazwa', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'opis', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'firma', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'serwer', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'kontoId', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'dataWyg', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'aktywna', '' . "\0" . 'AppBundle\\Entity\\domena' . "\0" . 'inne'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (domena $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazwa($nazwa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazwa', [$nazwa]);

        return parent::setNazwa($nazwa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazwa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazwa', []);

        return parent::getNazwa();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setInne($inne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInne', [$inne]);

        return parent::setInne($inne);
    }

    /**
     * {@inheritDoc}
     */
    public function getInne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInne', []);

        return parent::getInne();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirma($firma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirma', [$firma]);

        return parent::setFirma($firma);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirma', []);

        return parent::getFirma();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerwer($serwer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerwer', [$serwer]);

        return parent::setSerwer($serwer);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerwer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerwer', []);

        return parent::getSerwer();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontoId($kontoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontoId', [$kontoId]);

        return parent::setKontoId($kontoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontoId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontoId', []);

        return parent::getKontoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataWyg($dataWyg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataWyg', [$dataWyg]);

        return parent::setDataWyg($dataWyg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataWyg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataWyg', []);

        return parent::getDataWyg();
    }

    /**
     * {@inheritDoc}
     */
    public function setAktywna($aktywna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAktywna', [$aktywna]);

        return parent::setAktywna($aktywna);
    }

    /**
     * {@inheritDoc}
     */
    public function getAktywna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAktywna', []);

        return parent::getAktywna();
    }

}
